language: ruby
rvm:
  - 2.2

cache:
  bundler: true  # Doesn't seem to work
  directories:
  - node_modules

before_install:
  - nvm install 6
install:
  - bundle install
  - npm install

before_script:
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  # Decrypt and add deploy key (not necessary for private repo)
  - openssl aes-256-cbc -K $encrypted_c9381cfb26bc_key -iv $encrypted_c9381cfb26bc_iv -in .travis-deploy-key.enc -out .travis-deploy-key -d
  - chmod 600 .travis-deploy-key
  - eval "$(ssh-agent -s)"
  - ssh-add .travis-deploy-key

script:
  - grunt deploy -v
  - grunt purge_cloudflare_cache
